version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./backend/uploads:/app/uploads # Mapeamento explícito para uploads
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terapia_system
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/docker/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 90s # Tempo para o DB iniciar antes de começar a verificar

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data: {}
