services:
  app:
    container_name: medlm_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mapeia apenas as pastas de código, não a raiz inteira
      - ./backend:/app/backend
      - ./frontend:/app/frontend

      # O node_modules fica isolado dentro do container para não conflitar com o seu Windows/Linux
      - /app/backend/node_modules

      # Mapeamento limpo para os uploads
      - ./backend/uploads:/app/backend/uploads
    env_file:
      - .env
    command: node backend/server.js
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: medlm_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terapia_system
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/docker/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 50s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  phpmyadmin-aiven:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql-c6f9684-leandrommarquess-1808.d.aivencloud.com
      PMA_PORT: 13641
      PMA_USER: avnadmin
      PMA_PASSWORD: ${DB_AIVEN_PASSWORD}
    volumes:
      - ./backend/docker/phpmyadmin-aiven/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data:
